version: '3.9'
services:
  backend:
    image: node:16-alpine
    command: npm run dev
    restart: on-failure
    working_dir: /app/backend
    volumes:
      - .:/app/backend
    ports:
      - ${PORT}:3001
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001'] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  mysql:
    image: mysql:8.0.21
    container_name: db
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
