version: '3.9'
services:
  frontend:
    image: node:16-alpine
    command: npm run dev --host
    restart: on-failure
    working_dir: /app/frontend
    volumes:
      - ./front-end:/app/frontend
    ports:
      - ${FRONT_PORT}:3000
    environment:
      - BACK_PORT=${BACK_PORT}
      - BACK_HOST=backend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3000'] # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 10
  backend:
    image: node:16-alpine
    command: npm run dev
    restart: on-failure
    working_dir: /app/backend
    volumes:
      - ./back-end:/app/backend
    ports:
      - 3001:${BACK_PORT}
    tty: true
    stdin_open: true
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - BACK_PORT=${BACK_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@mysql:${DB_PORT}/${DB_NAME}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 15s
      retries: 5
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_NAME}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
